#!/usr/bin/env python
import os
import sys
import grp
import pwd

if os.getuid() != 0:
   print "{} : you need to be root to run this command".format(sys.argv[0])
   exit(1)

#user group path

uid = pwd.getpwnam(sys.argv[1]).pw_uid
gid = grp.getgrnam(sys.argv[2]).gr_gid

os.chown(sys.argv[3], uid, gid)
